-- MySQL Script generated by MySQL Workbench
-- sáb 07 out 2023 02:14:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadastroCliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastroCliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastroCliente` ;
USE `cadastroCliente` ;

-- -----------------------------------------------------
-- Table `cadastroCliente`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastroCliente`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastroCliente`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastroCliente`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_vendas_cliente1_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `cadastroCliente`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastroCliente`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastroCliente`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `preco` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idproduto_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC) VISIBLE,
  UNIQUE INDEX `preco_UNIQUE` (`preco` ASC) VISIBLE),
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastroCliente`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastroCliente`.`transacao` (
  `vendas_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`vendas_id`, `produto_id`),
  INDEX `fk_vendas_has_produto_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_vendas_has_produto_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_has_produto_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `cadastroCliente`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_has_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `cadastroCliente`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;